### ISSUE TITLE
No main tag or article tags were used. 

### ISSUE THREAD

**Issue by Thommond** [thienqui-communistspy/thienqui-communistspy.github.io#2]
https://github.com/thienqui-communistspy/thienqui-communistspy.github.io/blob/4a1b5c0429a6d13a088f8706bb22291d84049391/index.html#L9

**Comment by zachfedor** [comment]
This issue could be worded better. But yeah, @thienqui-communistspy you could swap these divs with some more semantic elements.

**Comment by kainguyen123-oss** [comment]
Changed page lay outs.
